version: '3'
services:
  ocean-server:
    build: .
    depends_on:
      - arango
    
  arango:
    image: arangodb/arangodb
    ports:
      - "8529"
    environment:
      - ARANGO_NO_AUTH: 1
    command: arangod --server.endpoint tcp://0.0.0.0:8529