version: '3'
services:
  ocean-server:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000"
      - "3001"
    depends_on:
      - arango
    
  arango:
    image: arangodb/arangodb
    ports:
      - "8529"
    environment:
      - "ARANGO_NO_AUTH=1"
    command: arangod --server.endpoint tcp://0.0.0.0:8529