version: '3'
services:
  ocean-server:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000"
      - "3001"
    depends_on:
      - arango
    environment:
      - "ARANGO_URL=http://arango:8529"
      - "ARANGO_DATABASE=ocean"
    
  arango:
    image: arangodb/arangodb
    command: arangod --server.endpoint tcp://0.0.0.0:8529
    ports:
      - "8529"
    environment:
      - "ARANGO_NO_AUTH=1"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"